apiVersion: v2
name: longhorn
description: Umbrella Chart for longhorn
type: application
version: 0.0.3
dependencies:
  - name: template-library
    repository: file://../template-library
    version: 0.0.3
  # https://artifacthub.io/packages/helm/argo/argo-cd
  - name: longhorn
    repository: https://charts.longhorn.io
    version: 1.9.2
