namespace:  {}

longhorn:
  ingress:
    enabled: false
  longhornUI:
    replicas: 1
  csi:
    attacherReplicaCount: 1
    provisionerReplicaCount: 1
    resizerReplicaCount: 1
    snapshotterReplicaCount: 1
  metrics:
    serviceMonitor:
      enabled: false
      additionalLabels:
        monitoring.instance: changeme
  preUpgradeChecker:
    jobEnabled: false
