external-dns:
  domainFilters:
    - kubaralearn-dev.stackit.run
  global:
    imagePullSecrets:
      - name: image-pull-secret
    security:
      allowInsecureImages: true
  provider:
    webhook:
      image:
        repository: ghcr.io/stackitcloud/external-dns-stackit-webhook
        tag: v0.3.2
  serviceMonitor:
    additionalLabels:
      monitoring.instance: kubaralearn-dev
    enabled: true
  txtOwnerId: kubaralearn-dev
externalSecrets:
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubaralearn-dev
  secrets:
    - data:
        - remoteKey: dns_zone_admin
          remoteKeyProperty: project_id
          secretKey: PROJECT_ID
        - remoteKey: dns_zone_admin
          remoteKeyProperty: auth_token
          secretKey: AUTH_TOKEN
      target: external-dns-webhook
namespace:
  labels:
    project-name: kubaralearn
    stage: dev
