apiVersion: v2
name: cert-manager
description: Umbrella Chart for cert-manager
type: application
version: 0.0.2
dependencies:
  - name: template-library
    repository: file://../template-library
    version: 0.0.3
  - name: cert-manager
    version: v1.18.2
    repository: https://charts.jetstack.io
