namespace: {}
secretStoreRef:
  kind: changeme
  name: changeme
oauth2-proxy:
  metrics:
    serviceMonitor:
      enabled: false
      labels:
        monitoring.instance: changeme
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 100Mi
