loki:
  backend:
    replicas: 0
  bloomCompactor:
    replicas: 0
  bloomGateway:
    replicas: 0
  compactor:
    replicas: 0
  deploymentMode: SingleBinary
  distributor:
    replicas: 0
  indexGateway:
    replicas: 0
  ingester:
    replicas: 0
  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    imagePullSecrets:
      - name: image-pull-secret
    limits_config:
      allow_structured_metadata: true
      volume_enabled: true
    pattern_ingester:
      enabled: true
    ruler:
      enable_api: true
    schemaConfig:
      configs:
        - from: "2024-04-01"
          index:
            period: 24h
            prefix: loki_index_
          object_store: filesystem
          schema: v13
          store: tsdb
    storage:
      type: filesystem
    useTestSchema: false
  minio:
    enabled: false
  monitoring:
    serviceMonitor:
      enabled: true
      labels:
        monitoring.instance: kubaralearn-dev
  querier:
    replicas: 0
  queryFrontend:
    replicas: 0
  queryScheduler:
    replicas: 0
  read:
    replicas: 0
  singleBinary:
    persistence:
      enabled: true
      size: 5Gi
    replicas: 1
  write:
    replicas: 0
namespace:
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    project-name: kubaralearn
    stage: dev
promtail:
  global:
    imagePullSecrets:
      - name: image-pull-secret
  serviceMonitor:
    enabled: true
    labels:
      monitoring.instance: kubaralearn-dev
    prometheusRule:
      enabled: false
