{{- if and .Values.bestPractices.enabled (dig "nginxIngress" "disallowIngressSnippets" "enabled" true (merge .Values)) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-ingress-nginx-custom-snippets
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/title: Disallow Custom Snippets
    policies.kyverno.io/category: Nginx Ingress
    policies.kyverno.io/subject: ConfigMap, Ingress
    policies.kyverno.io/minversion: "1.6.0"
    kyverno.io/kyverno-version: {{ .Values.global.kyvernoVersion | quote }}
    kyverno.io/kubernetes-version: {{ .Values.global.k8sVersion | quote }}
    policies.kyverno.io/description: >-
      Users that can create or update ingress objects can use the custom snippets
      feature to obtain all secrets in the cluster (CVE-2021-25742). This policy
      disables allow-snippet-annotations in the ingress-nginx configuration and
      blocks *-snippet annotations on an Ingress.
      See: https://github.com/kubernetes/ingress-nginx/issues/7837
spec:
  webhookConfiguration:
    failurePolicy: {{ dig "nginxIngress" "disallowIngressSnippets" "webhookFailurePolicy" "Fail" (merge .Values) }}
    timeoutSeconds: 30
  rules:
    - name: check-config-map
      match:
        any:
        - resources:
            kinds:
            - ConfigMap
      skipBackgroundRequests: true
      validate:
        allowExistingViolations: true
        failureAction: {{ dig "nginxIngress" "disallowIngressSnippets" "actionOverride" "Audit" (merge .Values)}}
        message: "ingress-nginx allow-snippet-annotations must be set to false"
        pattern:
          =(data):
            =(allow-snippet-annotations) : "false"
    - name: check-ingress-annotations
      match:
        any:
        - resources:
            kinds:
            - networking.k8s.io/v1/Ingress
      skipBackgroundRequests: true
      validate:
        allowExistingViolations: true
        failureAction: {{ dig "nginxIngress" "disallowIngressSnippets" "actionOverride" "Audit" (merge .Values)}}
        message: "ingress-nginx custom snippets are not allowed"
        pattern:
          metadata:
            =(annotations):
              X(*-snippet): "?*"
{{- end }}
