{{- if and .Values.bestPractices.enabled (dig "bestPractices" "disallowLatestTag" "enabled" true (merge .Values)) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/title: Disallow Latest Tag
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/minversion: "1.6.0"
    kyverno.io/kyverno-version: {{ .Values.global.kyvernoVersion | quote }}
    kyverno.io/kubernetes-version: {{ .Values.global.k8sVersion | quote }}
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      The ':latest' tag is mutable and can lead to unexpected errors if the
      image changes. A best practice is to use an immutable tag that maps to
      a specific version of an application Pod. This policy validates that the image
      specifies a tag and that it is not called `latest`.
spec:
  webhookConfiguration:
    failurePolicy: {{ dig "bestPractices" "disallowLatestTag" "webhookFailurePolicy" "Fail" (merge .Values) }}
    timeoutSeconds: 30
  background: {{ dig "bestPractices" "disallowLatestTag" "enableBackgroundScanning" true (merge .Values) }}
  rules:
  - name: require-image-tag
    match:
      any:
      - resources:
          kinds:
            - Pod
    skipBackgroundRequests: false
    validate:
      allowExistingViolations: false
      failureAction: {{ dig "bestPractices" "disallowLatestTag" "actionOverride" "Audit" (merge .Values)}}
      message: "An image tag is required."
      foreach:
        - list: "request.object.spec.containers"
          pattern:
            image: "*:*"
        - list: "request.object.spec.initContainers"
          pattern:
            image: "*:*"
        - list: "request.object.spec.ephemeralContainers"
          pattern:
            image: "*:*"
  - name: validate-image-tag
    match:
      resources:
        kinds:
          - Pod
    skipBackgroundRequests: false
    validate:
      allowExistingViolations: false
      failureAction: {{ dig "bestPractices" "disallowLatestTag" "actionOverride" "Audit" (merge .Values)}}
      message: "Using a mutable image tag e.g. 'latest' is not allowed."
      foreach:
        - list: "request.object.spec.containers"
          pattern:
            image: "!*:latest"
        - list: "request.object.spec.initContainers"
          pattern:
            image: "!*:latest"
        - list: "request.object.spec.ephemeralContainers"
          pattern:
            image: "!*:latest"
{{- end }}
