{{- if and .Values.bestPractices.enabled (dig "bestPractices" "requireReadOnlyRootFilesystem" "enabled" true (merge .Values)) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-readonly-root-filesystem
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/title: Require Read-Only Root Filesystem
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/minversion: "1.6.0"
    kyverno.io/kyverno-version: {{ .Values.global.kyvernoVersion | quote }}
    kyverno.io/kubernetes-version: {{ .Values.global.k8sVersion | quote }}
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      A read-only root file system helps to enforce an immutable infrastructure strategy;
      the container only needs to write on the mounted volume that persists the state.
      An immutable root filesystem can also prevent malicious binaries from writing to the
      host system. This policy validates that containers define a securityContext
      with `readOnlyRootFilesystem: true`.
spec:
  webhookConfiguration:
    failurePolicy: {{ dig "bestPractices" "requireReadOnlyRootFilesystem" "webhookFailurePolicy" "Fail" (merge .Values) }}
    timeoutSeconds: 30
  background: {{ dig "bestPractices" "requireReadOnlyRootFilesystem" "enableBackgroundScanning" true (merge .Values) }}
  rules:
    - name: validate-readOnlyRootFilesystem
      match:
        any:
          - resources:
              kinds:
                - Pod
      skipBackgroundRequests: true
      {{- with index .Values "kyverno-policies" "policyExclude" "require-readonly-root-filesystem" }}
      exclude:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      validate:
        allowExistingViolations: true
        failureAction: {{ dig "bestPractices" "requireReadOnlyRootFilesystem" "actionOverride" "Audit" (merge .Values)}}
        message: "Root filesystem must be read-only."
        pattern:
          spec:
            containers:
              - securityContext:
                  readOnlyRootFilesystem: true
{{- end }}
