ingress-nginx:
  controller:
    metrics:
      serviceMonitor:
        enabled: false
        additionalLabels:
          monitoring.instance: changeme
    image:
      digest: []
      digestChroot: []
