ingress-nginx:
  serviceAccount:
    automountServiceAccountToken: true
  controller:
    kind: DaemonSet
    admissionWebhooks:
      certManager:
        enabled: true
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        memory: 1024Mi
    config:
      # Disable strict path validation, to work around a bug in ingress-nginx
      # https://github.com/kubernetes/ingress-nginx/issues/11176
      # see also https://acme.cert-manager.io/docs/releases/release-notes/release-notes-1.18/
      strict-validate-path-type: false

namespace: {}
