apiVersion: v2
name: external-dns
description: Umbrella Chart for external-dns
type: application
version: 0.0.2
dependencies:
  - name: template-library
    repository: file://../template-library
    version: 0.0.3
  - name: external-dns
    repository: https://kubernetes-sigs.github.io/external-dns/
    version: 1.19.0
