# creates an ExternalSecret that looks for the specified remote-keys (remote secret names) to inject into webhook pod
externalSecrets:
  secretStoreRef:
    kind: "changeme"
    name: "changeme"
  secrets:
    - target: external-dns-webhook
      data:
        - remoteKey: "changeme"
          remoteKeyProperty: project_id
          secretKey: "PROJECT_ID"
        - remoteKey: "changeme"
          remoteKeyProperty: auth_token
          secretKey: "AUTH_TOKEN"

namespace:
  annotations: {}
  labels: {}

external-dns:
  txtOwnerId: changeme
  domainFilters:
    - changeme
  sources:
    - ingress
  policy: sync
  serviceMonitor:
    enabled: false
    additionalLabels:
      monitoring.instance: changeme
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 100Mi
  podSecurityContext:
    runAsNonRoot: true
    fsGroup: 65534
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    privileged: false
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    capabilities:
      drop: [ "ALL" ]
  provider:
    name: webhook
    webhook:
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
        limits:
          memory: 100Mi
      image:
        repository: changeme
        tag: changeme
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        capabilities:
          drop: [ "ALL" ]
      livenessProbe:
        httpGet:
          port: 8888
      readinessProbe:
        httpGet:
          port: 8888
      env:
        - name: AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: external-dns-webhook
              key: AUTH_TOKEN
        - name: PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: external-dns-webhook
              key: PROJECT_ID
